## Deliverable 3. Create a Travel Itinerary Map.

In [33]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [45]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,6,Kavieng,PG,85.37,scattered clouds,-2.5744,150.7967,Nusa Island Retreat
1,9,Zabid,YE,86.70,overcast clouds,14.1951,43.3152,مغرب التريبه
2,11,Avarua,CK,78.85,scattered clouds,-21.2078,-159.7750,Paradise Inn
3,15,Kapaa,US,85.98,scattered clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
4,17,Vaini,TO,82.56,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
...,...,...,...,...,...,...,...,...
202,666,Galveston,US,85.05,scattered clouds,29.3669,-94.9669,Crystal Suites
203,670,Chabahar,IR,85.53,overcast clouds,25.2919,60.6430,هتل گدروشیا
204,672,Cedar City,US,86.97,clear sky,37.6775,-113.0619,Hampton Inn Cedar City
206,677,Macrohon,PH,83.70,broken clouds,10.0797,124.9431,Banahaw Creek
207,680,Hami,CN,87.76,clear sky,42.8000,93.4500,Laoyutang Resort

In [46]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Current Description</dt><dd>{Current Description}</dd>

<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>


"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [47]:
# 4a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)

# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [48]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"]=="Guadalupe"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Guadalupe"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Coahuayana"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Lazaro Cardenas"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Acapulco"]

In [49]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0] 
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0] 
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0] 
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0] 
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]

In [50]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig=gmaps.figure()
vacation_itinerary=gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')

fig.add_layer(vacation_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [51]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,531,Guadalupe,MX,88.63,clear sky,25.6833,-100.2500,Fiesta Inn Monterrey Fundidora
1,148,Coahuayana,MX,81.27,broken clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
2,487,Lazaro Cardenas,MX,81.32,broken clouds,17.9583,-102.2000,HOTEL QUINTA ANTIGUA
3,658,Acapulco,MX,82.22,broken clouds,16.8634,-99.8901,HS Hotsson Smart Acapulco

In [52]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """

<dl>

<dt>Hotel Name</dt><dd>{Hotel Name}</dd>

<dt>City</dt><dd>{City}</dd>

<dt>Country</dt><dd>{Country}</dd>

<dt>Current Description</dt><dd>{Current Description}</dd>

<dt>Max Temp</dt><dd>{Max Temp} °F</dd>

</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [53]:
# 11a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))